name: Detect Drift

on:
  schedule:
    - cron: '0 5 * 1,7 0'
  workflow_dispatch:

jobs:
  detect_drift:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python 3.9
        uses: actions/setup-python@v5 
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run drift detection
        run: |
          export PYTHONPATH="${PYTHONPATH}:${pwd}"
          echo "Updated PYTHONPATH: $PYTHONPATH"
          python -m src.pipelines.run_drift_detection
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/*.html
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Created the latest drift report."
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}